name: nf-alchemish

channels:
    - conda-forge

dependencies:
    - python==3.13
    - pip
    - conda-forge::duckdb-cli
    - conda-forge::git
    - conda-forge::jq
    - pip:
        - "duvidnn>=0.0.1"
        - "eluent>=0.0.2.post1"
