name: nf-alchemish

channels:
    - conda-forge

dependencies:
    - python==3.12
    - pip
    - conda-forge::duckdb-cli
    - conda-forge::git
    - conda-forge::jq
    - pip:
        - "-e git+https://github.com/scbirlab/duvida.git@chem-splitting#egg=duvida[chem,splits,transformers]"
